In [3]:
import numpy as np

my_list = [1, 4, 6, 2]

arr = np.array(my_list) #created one dimensional array
print(arr)

[1 4 6 2]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
my_list1 = [1, 5, 7, 2]
my_list2 = [1, 7, 6, 9]
my_list3 = [5, 3, 6, 1]

arr = np.array([my_list1, my_list2, my_list3]) #created multi dimensional array

In [8]:
arr.shape

(3, 4)

In [4]:
arr1 = np.array([1,2,3,4,5,6,7,8])

arr[3]

2

In [12]:
arr1[:]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr1[:5]


array([1, 2, 3, 4, 5])

In [14]:
arr1[1:5]


array([2, 3, 4, 5])

In [15]:
arr1[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [16]:
my_list1 = [1, 5, 7, 2]
my_list2 = [1, 7, 6, 9]
my_list3 = [5, 3, 6, 1]

arr2 = np.array([my_list1, my_list2, my_list3])

In [19]:
arr2[0:2]

array([[1, 5, 7, 2],
       [1, 7, 6, 9]])

In [20]:
arr2[0:2,:]

array([[1, 5, 7, 2],
       [1, 7, 6, 9]])

In [18]:
arr2[0:2, 0:2]

array([[1, 5],
       [1, 7]])

In [21]:
arr2[:, :3]

array([[1, 5, 7],
       [1, 7, 6],
       [5, 3, 6]])

In [23]:
arr2[1:, 2:]

array([[6, 9],
       [6, 1]])

In [26]:
arr2[1:,1:3]

array([[7, 6],
       [3, 6]])

In [31]:
arr3 = np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr3 = np.arange(0,10, step=2)
arr3

array([0, 2, 4, 6, 8])

In [34]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [36]:
#copy functiom and brodcasting

arr3[3:] = 100
arr3

array([  0,   2,   4, 100, 100])

In [37]:
arr4 = arr3.copy()
arr4

array([  0,   2,   4, 100, 100])

In [39]:
##some conditions usefull in EDA

arr3 = np.arange(0,10)
# val = 2
arr3 < 2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [41]:
arr3*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr3/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [45]:
arr3[arr3<4]

array([0, 1, 2, 3])

In [46]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
##random distribution

np.random.rand(3,3)

array([[0.34497827, 0.65591012, 0.42529095],
       [0.07682034, 0.39494866, 0.61532889],
       [0.14722914, 0.08976541, 0.07263354]])

In [51]:
ass = np.random.rand(3)
ass

array([0.87448621, 0.73255726, 0.19163232])

In [53]:
arrx = np.random.randn(4,4)
arrx

array([[ 2.49397519,  0.05433255,  0.02082789, -0.47714944],
       [-1.3299412 , -1.07254516,  0.83980557,  0.54349789],
       [-0.82941607,  0.82516135, -0.49151498,  0.04252799],
       [ 0.02828033, -0.55916501,  1.92906855,  0.60396874]])

In [57]:
np.random.random_sample((1,3))

array([[0.74270983, 0.05950324, 0.82895725]])